input {
  file {
    path => "/var/log/nginx/access.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "nginx-access"
  }
}

filter {
  if [type] == "nginx-access" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
    date {
      match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
      target => "@timestamp"
    }
    mutate {
      convert => { "response" => "integer" "bytes" => "integer" }
      remove_field => [ "timestamp" ]
    }
  }
}

output {
  if [type] == "nginx-access" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "nginx-logstash-%{+YYYY.MM.dd}"
    }
  }
}
